require 'test/unit'
require_relative 'stairs_gain'

class StairsGainTest < Test::Unit::TestCase

  def test_01
    stairs = 'ygy'
    expected = 1

    assert_equal expected, StairsGain.new.stairs_gain(stairs)
  end

  def test_02
    stairs = 'gyggygggyygygyyyyyg'
    expected = 1

    assert_equal expected, StairsGain.new.stairs_gain(stairs)
  end

  def test_03
    stairs = 'gyyyyygggygggggyggggyggygyggg'
    expected = -14

    assert_equal expected, StairsGain.new.stairs_gain(stairs)
  end

  def test_04
    stairs =
        'ygggggggygggggyggggygyggggggggyygyyyygggggggyygyggyyygggggyyyyggggyygggyggggyggggyyyggggyygggygggggg'
    expected = -57

    assert_equal expected, StairsGain.new.stairs_gain(stairs)
  end

  def test_05
    stairs =
        'yyygyygyyggggyyggyyyyggyyggyyyyyygyyyyyyggyyyygggygyyggyyyyyygggygyyyyggygygggyyyyggygyggygygyggygg'
    expected = 22

    assert_equal expected, StairsGain.new.stairs_gain(stairs)
  end

  def test_06
    stairs = 'ygyyyyyygygyyygyygyyyggyyyyyygggyyyyyyygyyygyyyyyyyyyyyyyyygyyyyyyyygyyygyyyyyygyyyyyyygyyygyyggyygygggyyyyyyyyyggygyggygggyyygyyyyyyyygyggyyyyggyyyyggggyygyyygygyyyyyyyyyyyyyyyyggygygyygyyyyyyyyyyyyyyygyggyyyyggyyygygyyyyygyyyyyyygyygyyyyyyyyyygygyyygygyyyygyyyyyggyygyyyyyyyyyyyygyyyyyyyyyyyyygyyygyygyyygyygyygyyyyygyyyyyyygyygyyggygyyygyygggyyyyygyyyygygyyygygyyyyyyyyygyyygyyyyygyyyyyyyygyyyyyyygyyygygyygyygyyyyyyggggyyyyyyygygyyyyyyygyygygyyyggyygyyyggggyyygyyyygygyyyyyygyyyyyyyygygyygygyygyy'
    expected = 378

    assert_equal expected, StairsGain.new.stairs_gain(stairs)
  end


  def test_07
    stairs = 'gyygyyygyygggggygyygygggyygyygggyggyyggggyygyyyygyyyyygyygggyygggyyygyggyggyyggygygggyygygggyyygygyggggyggygyygyyyggggggyyggyygyyyygyygggggyyggyyyggyygyyggyyygygygyygyygygggyygggggyyyggyggygygggyyyggyygyggyyggggggyyyggggyggyygyygyggyygyyyggygyyyyyyygggygyyygggygyggyygggygyygyyyyyygygyyygggygyyyygygyggggggygggyyygyyygygggggggygyyyggyygygyygyygyggggygyygyygyygggyyygyyyygyyygyggyggyyggyggygyggyyyyygggygyggyggggyyyyyyygyyyyggyggggyyyyyyggyyggygygggggyygyyygyggyggyyygggygyggggyygyyggyyygygyyggyyggggyyygyggyyyyygggygggyyyygyygygyygyyyygygggyggggyggyggygggyygggyyyygygggyygyyyyyyggggyygygygyggyyyyyygggyyyyygggyyyggggggggygyggygygyggggygygygyggygyggyygyyggyygggyyggygygggygyyygyyyyyygyygygggyygggggggyyyyyygyggggyyggggygyyyyyggyyyggyyyyggyyggyggggyggyygggygygggggyyyggyyyggygggggyggggyyyyyyyggygyggyyyggygggggyyyyygyyggygggyyggyygyygggyyygyggygygggygyygygggggygyggygyggggygyyyyggyggyggyyggggyggyggygygygggyggyyyygygyyygyyggyygggygyyyyyggyyyyyygggygggygygyygygyygygygyygygggggygggggygyygyyyggggyggyygyggyyyyggygyyyggggyyggggggyyyygyyyyyyyggyggggggygyygygygygggggyygygygyggyyggyyygygggyygygyyyygggyygyyggggyyggggyyygyyygyggygyyyyggyygygyygggggggggyggyggyggyygggyyggyygyyygyggygyygggggggyggygygyggggyyygyggygyggyygyggygygggygyyyyygyygygyyyyyggyggyygyyyygggggygggyggygyyyygggyyygyygyygygggyyygyyyygggyggyyygyyyggyggygggyygggygygyygyyyyyyggyyygyyyggyyygggyggyyyygyygyygyyggggygyyyggggggyyyyygyygygyggyyygggyggygyyyggggygggyyggyygyyyyyyygyyygyygygygyygygygyyyyygyggygyggyygygggggggyggygyyggyygyyyyggyygygggyyggggyyygyyyggyygyyyyggggggygggygyyggyygggggggggygyggggggyyygyyygggggyygygyggyyyyyyggggyyggyggyyggyyygyyygygyygggyyyggggygyyggggyygyggygggggyyggygygggyygyggygyygyyyyyyyygyyyyyygggygggyggygggggyyyyyygyygyyyygyggyyggygyyygggyyyggggggygygyygygygyyyyygyyyyyyyyyygyygyggggyggyyyggyyyggyygggyyyggygygyyygggyyygygyygggygggyggyyyyygygyggyygygggygyygggggggyyyygygggyyggggyyyggygggygyyggggygyggyggyygggygyggyggyyygyygyyyyyyyggygggyggggyygyggyyyyyygyggyyyygygyggyygyygygyggyyggygyyyygyyyggyyyygyggyygyygyggyygygggggyggyyyyyyggyygggyggyyyygyggggygggyyyggyyyggygyygyyygyygyyyggyygyygyyyyggygyggygyyygggyggggggyygggyygyygygyygggygyyygyyggyggygggygygyggygggyygyyygyyyyyyggggyyyyggyyggyyygyyygyyyygygygggygyyygygygggggggggggggyyyyggggygyygygygygyggyggyygygygyggygyygyygyggyygggygyygyyyggggyggyggyyyygyggyyyygyyggyyyggyyygygyygggyygyyygygygyyyyggygggygggygyyyggggygggyyggyygggyygggyygyyggggyggygggyggyyggyygggyggyggygggyyygygggygygyyyyyggyggyyygyggygygygggyygygygyygggygyyygygggyyggggygygggyyggyggygyyyyygggggggyyygyygygygyyygygygyyygyggggyggyggyggggygyggyggygygyyygggyyggyyggyyyygyyygggyggyygggyyyyyygyygyggyggygyggygygygyyggyygygygggygyggyygyygggyyyyggyyggggyygyggygyyygygyyygygyyyyyyyyygyyggyygyygggggygygggyyyyggygggyyyyygyggyyggyygyyyggygyyggyygggyygyygyygyggygggggyyggggyggggygyygyggyygyyggyggggygyyyygyyygyyyyygggyyyygyyygyyyyyggggggygygygygygggyyyggggyygyyygyyyygyyygyyyyyyygyggyggygygyyyygyggyyggygyyygggggggygygygyggygyygygggygygyygyygggyyygyyygggyygyggyygygygggyyyygygyyggyyyggggggyyyygygggygyygyyyyyygygyygygyyyyygyygyyyygyygyyyyggygyyyyygyyyggyygyggygyygygygggygyggggyyggggyygygygyyggggyyyygyggygygyyyyggyygyyygyygyygyyygygyggygyyggyygygygggygygyggyggyyyyggyggyyyggyggggggygggyyyyyygyygggyyyygyygyggggyyggyyygyygyyyyyggyyyyyyggyyggyygygyyyygyygygygygyyygggygyyyyyggggyyygggggygygyyggggyyygggygggygyyyyggyyggyyggygygyygyyggyggyyyggggyyyyygggyggyygyyygyyyygygygggyyyyygyyyygggygggyggyyygyyygyyggyggygyggggygyyggyyygyggggggygyggyyggyyggygygyygyyyyggygyggyygygygyyygyyyggygyyygyggyyygyygygyyggggggggyggyyggyggyyygygyggygggggyyygygygggygyyggggyggyyggggygyyygygyygggyyyyggggygygyyggyyyggggygggyggygygyyyggggyyyyyyygggyggggyggyygggggggyygggygyyyyggggggyyggygyyggggygyyyggggygggyyyyyyggygyyyggyggggyggggyggyygyygyyyggyygyggggyygggygyyygyyyyygygyyygyyygggyyggygygyygyygyygyygggyygyyyyygggygyygygyygygyyggyygyyyggggygyygyygggyyygygygggygyggyggggyygygyyyggyyygyyyyyggyygygyyygyyygygyyyygygygyyyggygygyggggyygyyygyyyyyyygggyyygggyyyyygygyyyggyyyggyyygggygggyyyygyyyyggyygyggyygggggggyggggggggggggggggyyyyyygyggygygyygyyyyyygyggyygggggygygyggyyygggygyggygyyggyygyggyygygggyggyggygygggygygyggygyygyyggggyyggygyyygygygyyygygggggggygygyggyggyyygyyggygyyyyyygygyyygygggygggygyygggygygyyyggggyyggyyygyygyyygyggyygggyygggyggygggygygyygyygggyyggyyggygggyyggyyygyygygyyygyggygyyggyyyygggyggygggggygggyggygygyggygygggyyyygyyyggyggggygyyyygyyyggygygggyggygyyyyyyygyggyygyyygygggyyggyyggyggyygggygyyyyyyggyyygyyyggygygggggygygyyggyggggyggygygggygggygyygyyyygyyygyyyygyyyggyygyggyyygyggyygyyggggyyyyyyyygygygyyggggyygyygyyyygyygygygggyyygygygygggygygyggygygggyygggggyggggygggyyyggyygyggggygygyyggggyggyyggygyyyyggyyyyggggggggyyyyyggggygyyyyyygygyyygggyggyyyggyygggggggyygggyyggygyggyygyyyyygygggyggyygygyyyggygygyyyggygygyygyggyyyggyyggygygygygygygygygygygggyggyyyygygyygyyggyggyggggygggyyyyygyygggyggygyggyygggygyygyyygyygyyggyyyygyygggygggyyygyygyggygyyygggyygygggyggyygyygggggygyygyyggyyyygggggyyggggygyyyyyyyyggggyyyygggyggyyygggggggggggggygyygygggyyyggyygygyggyygyggggggggyyygggygyygygggyggggygyygyyyyyggyyygyygyyyygygyyyyygygyygggggggyyygggyygyyyygygggyyggyygggggyggggyggyggyyggygyygggggygyyyyyygggggygyyyyyyggyggyggggyygyggygygygyygyyyyygggyggggyygggyygggggygyygygygyggggyyggyyygyyyyygygyggyygyyyggggyyyggygygyyyyyyyyyygyggygygggggyyyygygggyggyygggggggggygygyyyggyggyygyggygyyygyygygyggyggyygyygggggyyyyyyyyggygyyggggyygggyyyyyygygyyggyyygygyygggggygggygyygygyggggyggyggygyggggyyggggygggyggygyggggggygyygyyyggggggggyyggyyyggggyyyygyyyyyyggggygygyyyyyggyyygygyygggyggyggggyyyyggggyyygygyggggyyyyggggyggygyggyyygyyygygyggyyggyyggygyygggyggygyyygggggygygyyygygygyyggygggygyyyygyygggyyyygygygygyyyggygggyyyygggygyyyggygyyygyyyyggyygygyyygyyygyygyyggggyyggyyygggggyggyyggygyggygggygyygyyyygygyyyygyyygyggggyyggggygggyyyggyygyygggygygggggyggggyyggyygyyygygygyggygyggggygyyygyygggyyggggyggggygygyyyygyyggggyyygyyyyyyyyggyyggyygyygyyyygyygggyygyyggyygyyyygygyyygyyyyggyyggyyggggyyyyyggggygyygyygyggyggyyggygyygygygygyggggygygggyggyygggyyyyyggggggygyyygyyyyygyygggygyyyygyggygyyyyyyygyggyggygggggyygygygggyyggyyggggggyygygyygggggggyggyyygyygggggggggygygggyyyygggyygygygyyyyygggyggggggyyyyygygggyyyygyygyggyyyygygggyggygggggggyygggygggyyyygggggyyygyygyygyyyyygyyggygyyggggggggggyyygggyyygggggyygyggyygyygggygggyggyggyyyyyyggyygyygggggyggyygyyyyyygygygyygyggyggyygyggygyyggygygygyggygyggyggyygygygygyyyyyyygygyyyggyyyyggyyygyyygygygyyyyyyggyyyyygygygyyyyyggygygygyyyggggyygyyggyyygggygyyyygygggygggygggyyyyyyygyygygyyggyygygygygygggggygyyyyyygygyggggyygggygygyyyygggyggggyyyyygyygygyyygggggyggggyygyyggyggyyyggggggyyyygyygggyyygygyygggyggyygygggggyggyyygyyyggygyygggggyygggggyyygyyyygggygygyyyygyggyygyggyygggggygyggygyyyyyyyyggggggygggggggyggygygyyygyygygyygggggyggyggggggyggggyyyygyyggyyyggggyggggyygggyyggygygyyygggyggygyyggyyyggygygyyggyyyyygyygyyyyygyygyyyyyyygygggyggyggggygggyyyyyygygggygygyygyygggyyyygygyggyyyyggyyygggyygygygygygygygygyygyggyyygggyggggyggyggggggygyyyygggyyggyyyyygygygggygyyggggygggyyggygyyyyygyggggggyggggyyggggyyggyyggygggyggygggggygygyyygygggyyygygyyggyyyggggyyygggyygygyyggyggyyyygyygyggyygygyggggyyyyyygggyyggygggyygggggyyygyyggygyyyygyygygygggggygyggygggyyyggggygyggyyygyyggyyygyyyggygggggyyggyyyyggyyyyyygggygggyyggyggyygyygygyygyygyyyyyygygygyggyygyygygygyggyygyyyygggyggyggyyygyygyyyyyygygygyyyggyyyyyygyyyygygggggyggyyyyyygygygygyygggyyyyyyygygyyggggyygyggygyygyygygyggygygyggygyyggggyyggyyygyygggggyyyggggygyyygyygygggygyygyyyyygyggyyggggygyygggyggyyyygggygggyyygggyygygggyygggyggyyyggygygyygggygygyyyyygyyggyygygyyyygggyggygyyyyygygyyggyyggggggggyyygyyyyyygygggygyyyyggygggyyygyyygyyyyyyyyygggygggggggyyggyyygyyyyggygyggggggygygyygyygygggyyyggggygygygyyyyyygyyygygyygyyygygyygygyyggygyyyyygggyggygggyyyyyyggyggggygyyggyggyggggyygyyyyyygyygggygygygggyyyyyggygyygggyyyygggyggygyyyygygyyyygygygyyyygyggggygygyyyyyyygyygygyygyggyggggyygygyyggyygygyygyyyggyyggyyygggyyggggyyyyggyyyyggygggyyygyyygggyygyggggggygyggygggygygggyyyygggygyyygyygyyggyyyggyyyyygyygyyggygygygyyygyygyyggyggyygyyyyyggggggyggyggygggyyygyyygygyggyygyyyyyggyyyygyygyggyyyygygggyyyyyyyggyygyggyyyyyggyggyyygyygygygyyyygyygyyyggyyggggggyygyyyggggyyyggyyygggyygyygygyggggggyyyggggyggygyggyygygyggyygyyggyyyggggygygyyyyygygyygyyggyyyyygyyggggggyyggygyyyyyyggygygyyyygggyyyyyggygygyyygggygygygyyggggyygygyyggyggyyggggyggggyggygggyyyggggyggyyygygyyggggggyyyyyyyyggyygyyyggggggygygygygggyygyggggygyygggyygyyggygyygggyygyyygggygggggggygygggyyyygyggggygygyygyyyyygggygygygygygygygggyygggggyyyyyygggyggggyyygyyyyggyygggyyygyyyyggyygggyygygygggyygyyyyygyygyggggyyggyyygygygygygyygggggygyyggyygyyygyyyyyygygygggyygyygyyggygyggygygyyggyyygygygyyyyygggyggygyggyyggyygyygyyyyggygyyyyyyyggygyyggyggggygyggyyggyggygggygyggyyyyggyygygygyyyggyygyyygyyygggyyygygyyyygyyygggygyyyyygyygygggygyyggygygggyyyyyyygygyygyyygygggyggygggygygggygyyggyyyyygygygyggygyyyygyygggyyggyygygyyyygyyggygyggggyygygggggyggygyyyyggyyyyyyggygggyygygygyggyygggygygygyyyyyyggygyyyygyyygyyyygyggygygggyyygygygyyggygyygygyyggggygygyyggggggyyyggyygygyggggygygggygyyggyyyggyggggyyyyyyggggygygyyyggyyygyyygyyygyyyyygggygyggyygyygyggyygyyygyygyggggygyyygyyygyyggygyyygyggggygygggygygyyygyygggygggyygggyyggygyyygygygggyygyggyygggyyygyygyyygggggygggyggyyggyygggygygygyyyygygygyyyggyyggggggggyyygyggyggyggggyyyggyyggyygygygggyygyggggyygggggyyygggygyyyggygyygyyyggygygyyyyyyyggyyyggygyggyyyggyyygyyggyggyggygyggyygyyyggyyggggygyygyyygyygggyggyggygyggggyggyyyygggyygggyyygyggggyygggggygggyggyyygyyyygygygyyyggggygygygyygggygyygygygggggygygygyyyggyyygygyygyggyyygyggyygggggggyygyggyyygyygygygyggyyyyyggyygggygyyggyygggggygyyygygyygygggggyyyggyyyygggyyggggygyggyyggggyyyggyyggggygyyygggygygygggyggggygyggygyggyyyyggggygyggygggyyggggygygyygggyyyggygggyygggyggyyyygyggyggygygyygyggyyyggggyggygygygggggyygggyyyyygggyggggyygyygygygyyygggygggyyyyyyggyygyggggygyygyggyggggyyygyggygygygyggggygygyygyyggyggygggyygggyggyggygygyyyygyyygyyyyggygygyggyyyygggyyygyyggyyygygyygyyggyyygyygyyygygygyyggyygyyggyggyyggyygygggygyggygyyyyggygyygyyyygygyyyyggyygyyyggyygyyygygggyygggyyygggyyygygygygyggygyyggygyygggyyyggyygygggyggggyyyyygyygggggygyygyyyygyygyyyygyyggygyyygygygyyggyyyggyygyygggggggyygy'
    expected = 94

    assert_equal expected, StairsGain.new.stairs_gain(stairs)
  end

  def test_08
    stairs = 'ggggggyyyyyyyyyygygygygyygygy'
    expected = 7

    assert_equal expected, StairsGain.new.stairs_gain(stairs)
  end

end